// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdjG24L_Ud92mloAmk654GLeTd786koLE',
    appId: '1:409195957863:web:27f054b6e00109ce404ec2',
    messagingSenderId: '409195957863',
    projectId: 'teste-tcc-446d5',
    authDomain: 'teste-tcc-446d5.firebaseapp.com',
    storageBucket: 'teste-tcc-446d5.firebasestorage.app',
    measurementId: 'G-HYRMYMLDKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQUqwdzuy0_wlid54a4NIM8FoiD_Kc630',
    appId: '1:409195957863:android:57475a702ce9840f404ec2',
    messagingSenderId: '409195957863',
    projectId: 'teste-tcc-446d5',
    storageBucket: 'teste-tcc-446d5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSP-eCwre2AV_klle2RC6JbE-73M94YPY',
    appId: '1:409195957863:ios:a48565275bb21e82404ec2',
    messagingSenderId: '409195957863',
    projectId: 'teste-tcc-446d5',
    storageBucket: 'teste-tcc-446d5.firebasestorage.app',
    iosBundleId: 'com.example.safeneighbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdjG24L_Ud92mloAmk654GLeTd786koLE',
    appId: '1:409195957863:web:5ceb998c4f9564f3404ec2',
    messagingSenderId: '409195957863',
    projectId: 'teste-tcc-446d5',
    authDomain: 'teste-tcc-446d5.firebaseapp.com',
    storageBucket: 'teste-tcc-446d5.firebasestorage.app',
    measurementId: 'G-3J62F0VDD8',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSP-eCwre2AV_klle2RC6JbE-73M94YPY',
    appId: '1:409195957863:ios:2dad938801819bd9404ec2',
    messagingSenderId: '409195957863',
    projectId: 'teste-tcc-446d5',
    storageBucket: 'teste-tcc-446d5.firebasestorage.app',
    iosBundleId: 'saf',
  );
}
